### ISSUE TITLE
Can’t add accessory.

### ISSUE THREAD

**Issue by putnik161** [datjan/esp8266-homekit-tempsensor#1]
Hi, please tell me, I can’t add a temperature sensor to the homekit, the application says Can’t add accessory.
WiFi connected, IP: 192.168.1.2
>>> [   8504] HomeKit: Starting server
>>> [   8510] HomeKit: Formatting HomeKit storage at 0x3fb000
>>> [   8541] HomeKit: Generated new accessory ID: 31:7B:38:88:98:43
>>> [   8598] HomeKit: Generated new accessory key
>>> [   8604] HomeKit: Preiniting pairing context
>>> [   8609] HomeKit: Using user-specified password: 555-11-123
>>> [   8629] HomeKit: Call s_mp_exptmod in integer.c, original winsize 6
>>> [  15325] HomeKit: Call s_mp_exptmod in integer.c, original winsize 5
>>> [  18745] HomeKit: Preinit pairing context success
>>> [  18750] HomeKit: Configuring MDNS
>>> [  18756] HomeKit: MDNS begin: Temperature Sensor, IP: 192.168.1.2
>>> [  18763] HomeKit: Init server over
Current temperature -127.0
Free heap: 41224, HomeKit clients: 0
Free heap: 41888, HomeKit clients: 0
>>> [  24783] HomeKit: Got new client: local 192.168.1.2:5556, remote 192.168.1.9:56886
>>> [  24792] HomeKit: [Client 1073680676] Pair Setup Step 1/3
Current temperature -127.0
Free heap: 40288, HomeKit clients: 1
>>> [  32454] HomeKit: [Client 1073680676] Pair Setup Step 2/3
>>> [  32465] HomeKit: Call s_mp_exptmod in integer.c, original winsize 6
>>> [  42446] HomeKit: Call s_mp_exptmod in integer.c, original winsize 5
Current temperature -127.0
Free heap: 39568, HomeKit clients: 1
>>> [  47564] HomeKit: [Client 1073680676] Pair Setup Step 3/3
>>> [  47593] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c
>>> [  48314] HomeKit: Added pairing with C51685D2-9FE3-45A4-91E8-8F0C7BFA37A3
>>> [  48385] HomeKit: Free saved_preinit_pairing_context
>>> [  48390] HomeKit: [Client 1073680676] Successfully paired
>>> [  48447] HomeKit: [Client 1073680676] Disconnected!
>>> [  48452] HomeKit: [Client 1073680676] Closing client connection
>>> [  48836] HomeKit: Got new client: local 192.168.1.2:5556, remote 192.168.1.9:56887
>>> [  48856] HomeKit: [Client 1073683228] Pair Verify Step 1/2
>>> [  49175] HomeKit: Free heap: 41688
>>> [  49352] HomeKit: [Client 1073683228] Pair Verify Step 2/2
>>> [  49359] HomeKit: [Client 1073683228] Found pairing with C51685D2-9FE3-45A4-91E8-8F0C7BFA37A3
>>> [  49382] HomeKit: Call ge_double_scalarmult_vartime_lowmem in ge_low_mem.c
>>> [  50112] HomeKit: [Client 1073683228] Verification successful, secure session established
>>> [  50121] HomeKit: Free heap: 41800
>>> [  50278] HomeKit: [Client 1073683228] Get Accessories
>>> [  50349] HomeKit: [Client 1073683228] Disconnected!
>>> [  50354] HomeKit: [Client 1073683228] Closing client connection
Free heap: 44144, HomeKit clients: 0
Current temperature -127.0
Free heap: 44144, HomeKit clients: 0
Free heap: 44144, HomeKit clients: 0
Current temperature -127.0
Free heap: 44144, HomeKit clients: 0

**Comment by datjan** [comment]
Hi,

It is because of the not correct temperature value.

You current temperature is -127.0 and this will not be accepted by HomeKit.

Please check the connection to the DS18B20. 

Otherwise you need to limit the value of "temperature_value" within this part of code:
float temperature_value = sensors.getTempCByIndex(0); // SETUP read your real sensor here.

Accepted values are -100 to 100

**Comment by putnik161** [comment]
> Привет,
> 
> Это из-за неправильного значения температуры.
> 
> Ваша текущая температура составляет -127,0, и это не будет принято HomeKit.
> 
> Пожалуйста, проверьте подключение к DS18B20.
> 
> В противном случае вам необходимо ограничить значение «temperature_value» в этой части кода: float Temperature_value = Sensors.getTempCByIndex(0); // НАСТРОЙКА считывает ваш реальный датчик здесь.
> 
> Допустимые значения: от -100 до 100.

thanks, it helped, I broke my head for two days I could not understand why it does not work
